nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: quay.io/cloud-architecture-workshop/globex-store-db
  pullPolicy: IfNotPresent
  tag: latest

podSecurityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

podAnnotations: {}

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  timeoutSeconds: 1
  initialDelaySeconds: 5
  tcpSocket:
    port: 5432

readinessProbe:
  timeoutSeconds: 1
  initialDelaySeconds: 5
  exec:
    command:
    - "/bin/sh"
    - "-i"
    - "-c"
    - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'

service:
  enabled: true
  portName: postgresql
  port: 5432
  containerPort: 5432

serviceAccount:
  create: true
  annotations: {}
  name: ""

pgsql:
  user: globex
  password: globex
  database: globex
  adminPassword: 
  debeziumPassword: debezium

persistence:
  mode: ephemeral
  capacity: 20Gi

argocd:
  enabled: true
  syncwave: "-2"

db:
  deploy: true