nameOverride: "kafka"

kafka:
  enabled: true
  version: 3.6.0
  cluster:
    replicas: 2
  zookeeper:
    replicas: 3
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 200M
  config:
    autoCreateTopics: false
    defaultReplicationFactor: 2
    offsetsTopicReplicationFactor: 2
    transactionStateLogReplicationFactor: 2
    transactionStateLogMinIsr: 2
    minInsyncReplicas: 1
    interBrokerProtocolVersion: '3.6'
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: 500m
          memory: 500M
        requests:
          cpu: 250m
          memory: 250M
    userOperator:
      resources:
        limits:
          cpu: 250m
          memory: 250M
        requests:
          cpu: 150m
          memory: 150M
  resources:
    limits:
      cpu: '1'
      memory: 2G
    requests:
      cpu: 300m
      memory: 500M

bootstrapServer: 

namespace:

authentication:
  clientId: globex
  clientSecret: globex
  securityProtocol: SASL_PLAINTEXT
  saslMechanism: SCRAM-SHA-512

authorization: simple

argocd:
  enabled: true
  syncwave: "-2"
