apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  annotations:
    app.openshift.io/connects-to: |
      [{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Values.inventoryService.name }}"},{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Values.catalogDb.name }}"}]
  labels:
    app.kubernetes.io/name: {{ .Values.catalogService.name }}
    app.openshift.io/runtime: spring
    {{- include "catalog-app.selectorLabels" . | nindent 4 }}
  name: {{ .Values.catalogService.name }}
spec:
  replicas: {{ .Values.catalogService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.catalogService.name }}
      {{- include "catalog-app.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ .Values.catalogService.name }}
      {{- include "catalog-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image:  "{{ .Values.catalogService.image.repository }}:{{ .Values.catalogService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.catalogService.image.pullPolicy }}
          name: {{ .Values.catalogService.name }}
          ports:
            - name: {{ .Values.catalogService.ports.httpPortName }}
              containerPort: {{ .Values.catalogService.ports.httpPort }}
              protocol: TCP
          resources: {}
          env:
            - name: JAVA_OPTIONS
              value: -Dspring.profiles.active=openshift
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.catalogDb.secret.name }}
                  key: database-name 
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.catalogDb.name }}:5432/${POSTGRESQL_DATABASE}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.catalogDb.secret.name }}
                  key: database-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.catalogDb.secret.name }}
                  key: database-password
            - name: INVENTORY_URL
              value: {{ .Values.inventoryService.name }}:8080
      serviceAccountName: {{ include "catalog-app.serviceAccountName" . }}
      serviceAccount: {{ include "catalog-app.serviceAccountName" . }}
