{{- if eq .Values.scope.namespace true -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "streams-console.labels" . | nindent 4 }}
  name: {{ include "streams-console.name" . }}-prometheus
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
{{ end }}
