inventory:
  inventoryService:
    name: inventory  

catalog:
  catalogService:
    route:
      enabled: true
  inventoryService:
    name: inventory

globex-ui:
  globexUi:
    route:
      enabled: true
    env:
      trackActivityService:
        url: http://activity-tracking:8080
        postActivityPath: /track
      catalogService:
        url: http://catalog:8080
        getProductsPath: /services/products
        getProductListPath: /services/product/list/
      recommendationEngine:
        url: http://recommendation-engine:8080
        getRecommendedProductsPath: /score/product

recommendation-engine:
  route:
    enabled: true
  kafka:
    bootstrapServer: localhost:9092
    securityProtocol: ""
    saslMechanism: ""
    userId: ""
    password: ""

activity-tracking:
  route:
    enabled: true
  kafka:
    bootstrapServer: localhost:9092
    securityProtocol: ""
    saslMechanism: ""
    userId: ""
    password: ""