apiVersion: v1
kind: Service
metadata:
  name: {{ include "cashback-service.name" . }}
  labels:
    {{- include "cashback-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "cashback-service.selectorLabels" . | nindent 4 }}
