apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recommendation-engine.name" . }}
  labels:
    {{- include "recommendation-engine.labels" . | nindent 4 }}
    app.openshift.io/runtime: quarkus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "recommendation-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "recommendation-engine.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "recommendation-engine.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.ports.httpPortName }}
              containerPort: {{ .Values.ports.httpPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /deployments/config
              name: config
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "recommendation-engine.name" . }}
