apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalog-db.name" . }}
  labels:
    {{- include "catalog-db.labels" . | nindent 4 }}
    app.openshift.io/runtime: postgresql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "catalog-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "catalog-db.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.ports.pqsqlPortName }}
              containerPort: {{ .Values.ports.pgsqlPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: {{ include "catalog-db.name" . }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: {{ include "catalog-db.name" . }}
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: {{ include "catalog-db.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      serviceAccountName: {{ include "catalog-db.serviceAccountName" . }}
