apiVersion: v1
kind: Service
metadata:
  name: {{ include "activity-tracking.name" . }}
  labels:
    {{- include "activity-tracking.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "activity-tracking.selectorLabels" . | nindent 4 }}
